ReinterpretDataLayer, fix dyn_size_ext placeholder context (#1262)
When some dim was initially created inside a CondLayer, it had the wrong control flow context.
This lead to the error:

tensorflow.python.framework.errors_impl.InvalidArgumentError: Retval[0] does not have value

This fixes it.