small Python 2 fix
TypeError: super() argument 1 must be type, not classobj

The way we use `super` only works for new-style classes.
Python 2 needs to be told explicitly this way to use a new-style class.